### ISSUE TITLE
Helle, how to load a xx.wav beform use audiocapture get frequency

### ISSUE THREAD

**Issue by marshal-it** [kwstasg/WAC#1]
Helle, how to load a xx.wav beform use audiocapture get frequency

**Comment by kwstasg** [comment]
you can simply put the .wav into your scene and make sure you have the autoplay checked.
just have in mind that this plugin's main purpose is   to get the frequencies of everything is played live from your windows default audio device. in case you want to load and get frequencies from a specific external audio file outside your content folder i recoment you use exi's sound viz plugin
