### ISSUE TITLE
4.22 Update?

### ISSUE THREAD

**Issue by astralmedia** [kwstasg/WAC#10]
Hey! Was curious if you had any plans to update this to support 4.22?

If not, maybe you could give me an idea of what needs to be done, and me and my guys can try to do it. I'd be open to submitting a PR for a fix.

Thanks!

**Comment by kwstasg** [comment]
Plugin has just been updated to 4.25 hope that helps

**Comment by astralmedia** [comment]
You are awesome! 👍
