### ISSUE TITLE
Viewport OK... Standalone Bad... Packaged Broked

### ISSUE THREAD

**Issue by Zalotron** [kwstasg/WAC#11]
I have a weird issue... My project runs OK in windows editor. But in standalone version the audio capure has too many fluctuations, more than 60% of the playback are bizarre fluctuations, And 30 seconds later stop working, there is no more freqs values, is all black, and I have to re-open...
And in the packaged version there is no data at all, its all black from the beggining.
I dont know what to do rlly

**Comment by kwstasg** [comment]
Maybe you should try the latest version there are some issues fixed

**Comment by Zalotron** [comment]
I want to say thanks for your work and I also want to show you what I did with your plugin.
I have been used this intro for my twitch channel for more than a year, and I was working on a new one.
Here two clips. I hope you be proud ;)
https://www.twitch.tv/zalotron/clip/ExuberantHilariousCodShadyLulu?filter=clips&range=all&sort=time
https://www.twitch.tv/zalotron/clip/EntertainingGracefulCobblerVoHiYo?filter=clips&range=all&sort=time

**Comment by kwstasg** [comment]
WOW!!!! you really put it in good use!!!! I feel very honored!
