### ISSUE TITLE
I cant generate clean proyect

### ISSUE THREAD

**Issue by Zalotron** [kwstasg/WAC#12]
Hi, I'm a little bit stressed with this. I downloaded UE4 4.20 the plugin, and the demo proyect, and, I can not open the demo proyect, niether rebuild from source. And i can not compile the UE4 4.20 soruce code with the plugin merged, I dodnt know what to do
Im a streamer and I use a scene with music visualization as a "stream starting" scene... And I have to play the project in the editor. I need to generate a standalone version and I cant build it. All I can do right now is create a project in 4.17 with the plugin, but can not generate a standalone build about. I pretty sure that I've been doing something wrong. What is the procedure to create a functional clean proyect without error for standalone compiling?
Ty btw, and srry for the inconveniences

**Comment by kwstasg** [comment]
you can just add the plugin to your own brand new project, just put it in the plugins folder (create the folder if you dont use other plugins)  then it will appear in your ue plugin tab
