### ISSUE TITLE
Incompatible software

### ISSUE THREAD

**Issue by t3r3nc3101** [kwstasg/WAC#2]
Just wanting to leave a heads up that this plugin causes ue4 to crash on begin play if you have "Nahimic" audio enhancement software running. I know not many people would, but I did, and it took me a while to figure out, so I though I'd share.
Great plugin though, thanks!

**Comment by kwstasg** [comment]
Thank you for mention this, to be honest im not familiar with Nahimic audio enhancement software so i haven't run any tests please fill me up with the UE4 ver you are using

**Comment by t3r3nc3101** [comment]
I've tried it in 4.16, 4.17 & 4.17-flex build.
The nahimic program can just be closed from the taskbar tray, then UE4 doesn't crash, so it's not a huuge problem.
