### ISSUE TITLE
Has anyone been able to successfully package a project with this plugin?

### ISSUE THREAD

**Issue by gitumar** [kwstasg/WAC#6]
I tried to package a project on ue4 4.20.3 with the plugin installed and it failed. I know the ue4 audio visualization fails to package also. Does this suffer from the same problem? Thanks

**Comment by gallonmate** [comment]
This plugin packages and works fine for me on windows 64 bit.

**Comment by gitumar** [comment]
@gallonmate  Thats awesome! I was not able to package using default settings. Just to test it I opened up a blank C++ project in ue 4.20.3 and packaged it and I had no problems and got the .executable. When I import the plugin to that same project and try to package, i get an error and it says unknown.
What settings did you have to change to get this packaged?

**Comment by gallonmate** [comment]
I didn't do anything special. I just setup a level to package and set the default level/gamemode. If you download the demo project that has the sample visualizer levels it should export as is.

**Comment by gitumar** [comment]
@gallonmate TY for the reply. I successfully packaged the demo project! So I know it can be done. I will try again to package my own project with the plugin imported. Will update this thread.

As an aside, I deleted the sln file, right clicked the project and generate visual studio files before I even launched the demo project in the PIE, not sure if that was even necessary but I did it anyway.

**Comment by gitumar** [comment]
Successfully packaged custom project with plugin imported on ue4 4.20.3
