### ISSUE TITLE
Integrating with BTrack

### ISSUE THREAD

**Issue by astralscott** [kwstasg/WAC#7]
Hello! First off, thank you for this software! It's just what we need.

I am trying to integrate this with https://github.com/adamstark/BTrack to figure out the BPM of the incoming audio...

However, in the BTrack docs, it needs us to fill a double precision array with one frame of audio samples...

Can I get that using WAC? I am just confused as to how to go about figuring that data out.

Thanks again!

**Comment by astralscott** [comment]
Also, I notice we need to use the https://github.com/erikd/libsamplerate library, which is only available for win32...is it possible to use this with win64 even tho the required library only supports 32?

**Comment by gallonmate** [comment]
Unfortunately, that beat tracking code is licensed under GPL which is not compatible with the UE4 license.

**Comment by astralscott** [comment]
Thanks!
