### ISSUE TITLE
4.21 Update?

### ISSUE THREAD

**Issue by astralscott** [kwstasg/WAC#8]
Just wanted to check in and see if this would be updated to 4.21? Thank you!

**Comment by Derjyn** [comment]
I second this. I tried to compile for 4.21, and was getting several issues. I'll come back later after work, and update with some specific error/warning messages.

**Comment by MaxPowerz** [comment]
I updated it to work with 4.21.2 and fixed the Desync/Noise issue
Here's a link to the plugin
WAC 4.21.2 Fixed.zip   10.1 MB 
https://mega.nz/#!VhFDUITD!XT3nvPEX2b_PbJpXydOIRP8zFuI8NJ0QpxVhGejVgvY

Just add it to the plugins folder in your project and it'll load in 4.21.2
It'll come up with a dialogue box saying it's designed for 4.20, 
Just click ok and it will still work.

**Comment by kwstasg** [comment]
Plugin has just been updated to 4.25 hope that helps
